---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: servicex-postgresql-secret-d247bb8h49
  namespace: sthapa
spec:
  encryptedData:
    postgresql-postgres-password: AgAycOx1ne0Xze3EePnz4qM1jc3owaZmw8/ElKwJlU/xILWqjA7eWew39wc2p6XfGAKBnseQUHc+04lPVL+zKu+yQwxENH4iCwVb8hLyCMrY0H4LqqsiCejGwrGSAtw1sy4Ouksmpdl7/zHIExfyEAow0OfWUGG3S+HUe/u9PhYN8hQFpxUdYjO+KsnoP6em/eTBBm9icyk3VOY1Eep8ujF/5A1lMMSTQ2EMFDqnWhLef2c/LXu5miDmpBfk3PE6Lt6Fd8yzpz5KfIkGfEOijCUDpDm3+UrnowpqFtvU6AIfqi4ZzxmHUdMeSlQakLXbK9kUentBR+GrRCvfe4Z9VfUzP2xNB9bt+nyWVDrB+DqkMtNVu4aikf4T1oGQMf4aWWuFctscUpwR4YT/sh0MChkkyd85qhHUsWX7TaRqogCu5vBCRlQKHFi6yDudt2IksyROizU+byxdcCx0agG0HVfCQ5uwjpPt/XdYB49Xb79h3PH8d7tIVBZLOMuJgxj0SkdIShj1blClNvwiW8vUcii3aPz5/vfhkLugjZ62BKQnyd3My+uG7RYiVU9txTLMDwnBws/GremihSbBEbNQN+bnE/ZMYzReyqBlMYSFlakxCzQL4a2JJUkskXKRs0x6DM4yqbfZd3xiU8vzGOS2FzkNa1Rm5ya68R060QvRu/YDOPfv8zyPuHV3HffTqcygNse5qZDca3Wmi0Om
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: servicex-postgresql-secret-d247bb8h49
      namespace: sthapa
    type: Opaque
