apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: servicex-rabbitmq-secret-c8658ct6mh
  namespace: sthapa
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgAawuWwMz8T0k5gdSRJy7StjvKaodZhpu7XruWMm4mhGBDi8KIRLmgLZU5eNLVHJzkbnfLTpdPD+38tFKbPnVNKsTRwhEyJgdUzRwxQV4ywWjqjdYm55o5GLsp8mGsJn4gXH9puNZmWtig+UJAkLZiYDEdEFAUVooN71pAPLZOiuf14Hc5/OOoCEFE6feAfxPlyuSOtPPV4mL6TeNq/734CzobF7i1xgxCLLUN3B0x2dsWwgRXTTyl6r8+M5B2IsBvTB0DkCVbA9inyCYTKnoqPX90UGfjueo82ILM31sLsj5s4Q6OnokxTZlNg76mnpVTcxODy2N+jjoyNhah4uZduNMiaOhx5wehI/JGVa++bgKwDBNJYCGBW7bkT9k8i6ZgpePh8gjLV6OJJ0LNCCtVSYeLzZyLgxK5+OxA1aVVVI1MtA6aAECZ/GOKnjCte+Jao5JA0ws96+htzW969ajcPQA4niaIDlyzoGOxmPACa394j8beGy2ReVfT4ifgak9C7bK+igeBkqioLHYrawRZBtE0hWIvx462pz698nJUBF5+NjBp3tEPEdg91JRTa5vjA8lzajuyHtL1ZlAWGDVjNqPObIbE5wkcDkOr0tQ1XLz7dJ9CosVQGLcQFfT5D+fkbRjb9fKSj5uoWPDHLb/yVFLbbRxuWxQx9GMgbPeYSfRvXiRrQglVbdRkRI+E0S6VPwbHIPwMxCCWHjkxAmzFYAclD6vTbXgwK+xyO++YwrDU=
    rabbitmq-password: AgCa3r4UgC4nCgY3zOlvhhOtpKEMZ8VhRfqAEEH7RjijcbQ/bvFNIESqoo5zP0Ym+wRC94Qt1BnSWp4veXyeo9tc+9vhj3kGKhSIv5Nn1qkpOu+5NmU0dGS/qF29UYSc7r7nM2Tau0oUrkdzuFoVWzCnypPS0nr4maczNa04T7IrPy3AvaLyRiqR6FoQPKPNIRjKphvWs6dG3eUF5FSveyDlfhTTt3YB3IfEu+zwEmHGC0QFykWhxp6UV5lQ3rdrlCwR7Ul3hup0My5csRiA9R6uCoOIYmCC4IqA3LyTGfrqrpQDzsnqiBSWGN1jexr27a2+W+PnodkhKbblH4UoPcXka7QVGPat6+k09vk/t85posBxgrZSBQQhNO8kCkoHSaZa8VCFAqvFupjqdczEiO2jYUmKbg4Miovkl2OUAWZNXiwabWRLxQqtS0ae9bstDqCp8GLbxYGEletHwEAybm3EYOVsT151VbO3xQXTm+7BwjxWXVbtTempJa9kYcDW9I/iFLkzd9G7mEadSCKjiEu1WMsacZvgK6l5CCPjvZ+bhkS47+hPcuZBzKlMPe3WdorV72RBPbi8YG3KnxfAA/gVfa5uI3AJrUx0TdzbW/42pKCgG7zAFg6VZKNWlfBr/hqtKG9JuOSWjVjQ9kkWw/E84l7M5xO0kU2niIw4buhTsswExCq8cHRPQzMvpDzXSv0LpwW30PKQkY3V
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: servicex-rabbitmq-secret-c8658ct6mh
      namespace: sthapa
    type: Opaque

