apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/servicex

resources:
  - servicex-values.yaml
  - postgresql-secret.yaml
  - rabbitmq-secret.yaml
  - minio-secret.yaml

secretGenerator:
  - name: servicex-postgresql-secret
    type: Opaque
  - name: servicex-rabbitmq-secret
    type: Opaque
  - name: servicex-minio-secret
    type: Opaque
